// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5_wqyV9d511tuaAbLUYEPn5Q3ipxpeJQ',
    appId: '1:580691276316:web:c7c8df8c4a655c899d65d9',
    messagingSenderId: '580691276316',
    projectId: 'newproject-51613',
    authDomain: 'newproject-51613.firebaseapp.com',
    storageBucket: 'newproject-51613.firebasestorage.app',
    measurementId: 'G-TTV262XTCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFUhvoNi80_LLler_QiW_zESxzYWJfnQE',
    appId: '1:580691276316:android:b77e217646561e779d65d9',
    messagingSenderId: '580691276316',
    projectId: 'newproject-51613',
    storageBucket: 'newproject-51613.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwJQfrX_a9BKiD2vi0b6Sl5Plk6uT7DLU',
    appId: '1:580691276316:ios:302085f25e3bbe9c9d65d9',
    messagingSenderId: '580691276316',
    projectId: 'newproject-51613',
    storageBucket: 'newproject-51613.firebasestorage.app',
    iosBundleId: 'com.example.testingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwJQfrX_a9BKiD2vi0b6Sl5Plk6uT7DLU',
    appId: '1:580691276316:ios:302085f25e3bbe9c9d65d9',
    messagingSenderId: '580691276316',
    projectId: 'newproject-51613',
    storageBucket: 'newproject-51613.firebasestorage.app',
    iosBundleId: 'com.example.testingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5_wqyV9d511tuaAbLUYEPn5Q3ipxpeJQ',
    appId: '1:580691276316:web:d2bb3df3fde96fad9d65d9',
    messagingSenderId: '580691276316',
    projectId: 'newproject-51613',
    authDomain: 'newproject-51613.firebaseapp.com',
    storageBucket: 'newproject-51613.firebasestorage.app',
    measurementId: 'G-6YY5Q6G0GD',
  );
}
